version:  '3'
services:
  # juice-shop:
  #   image: bkimminich/juice-shop
  #   #build:
  #   #  dockerfile: Dockerfile
  #   #  context: ./juice-shop
  #   ports:
  #       - '3000:3000'
  log4shell:
    image: ghcr.io/christophetd/log4shell-vulnerable-app
    ports:
      - 5000:8080
  nginx-reverse-proxy:
    #build:
    #  dockerfile: Dockerfile
    #  context: ./nginx-reverse-proxy
    ports:
      - '80:80'
    ipc: host
    #image: checkpoint/infinity-next-nginx
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
    #  - ./nginx-reverse-proxy/default:/etc/nginx/conf.d/default.conf
    - ./nginx-reverse-proxy/default:/etc/nginx/conf.d/default.conf:ro
  agent-container:
    ipc: host
    volumes:
      - ./agent-container/data:/etc/cp/data
      - ./agent-container/conf:/etc/cp/conf
      - ./agent-container/logs:/var/log/nano_agent
    #build:
    #  dockerfile: Dockerfile
    #context: ./agent-container
    image: checkpoint/infinity-next-nano-agent    
    command: ["/cp-nano-agent", "--token", "$TOKEN"]

